title = "Hack Schulich"
baseURL = "http://henryhe.me/hackschulich/"
tags = ["hackathon", "university", "tech", "medicine"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
publishDir = "docs"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Medical Hackathon at Western University"
    author = "Henry He"
    description = "Medical Hackathon at Western University"
    logoBig = "/images/hack-logo.png"
    logoSmall = "/images/hack-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = ""
    linkedin = ""
    github = ""
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Apply"
    url  = "https://hackschulich.typeform.com/to/jMBOhW"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
